spring:
  datasource:
    url: jdbc:mysql://115.85.182.96:33906/appservice?characterEncoding=UTF-8&amp&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: apiuserk21
    password: dufTlagltkfwk2021

#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/ourstock?characterEncoding=UTF-8&amp&serverTimezone=Asia/Seoul
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password:

    hikari:
      connection-timeout: 10000
      validation-timeout: 10000
      idle-timeout: 10000
      max-lifetime: 580000

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        format_sql: true
#        show_sql: true

#server:
#  port: 9010

jwt:
  secret: OurstockWas2021ServiceStaRtSeCretKeY


logging:
  level:
    "[org.hibernate]" : ERROR


server:
  port: 9090


systempassword: 2021tjdrhdgkqtlek

